version: "3"

services:
  gateway:
    env_file:
      ./.env
    build: ./gateway/.
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
  customer:
    build: ./customer-service/.
    ports:
      - "${CUSTOMER_PORT}:${CUSTOMER_PORT}"
    depends_on:
      - mongo
  user:
    build: ./user-service/.
    ports:
      - "${USER_PORT}:${USER_PORT}"
    depends_on:
      - mongo
  photo:
    build: ./photo-service/.
    ports:
      - "${PHOTO_PORT}:${PHOTO_PORT}"
    depends_on: 
      - minio
  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - c:/data/db:/data/db
      - c:/data/configdb:/data/configdb
  minio:
    image: minio/minio
    volumes:
      - c:/data/data1:/data1
    ports:
      - "${STORAGE_PORT}:9000"
    command: server minio/data1
