version: "2"

services:
  gateway:
    env_file:
      ./.env
    build: ./gateway/.
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
  customer:
    env_file:
      - ./customer-service/.env
    build: ./customer-service/.
    ports:
      - "${CUSTOMER_PORT}:${CUSTOMER_PORT}"
    depends_on:
      - mongo
      - rabbitmq
  user:
    env_file:
      - ./user-service/.env
    build: ./user-service/.
    ports:
      - "${USER_PORT}:${USER_PORT}"
    depends_on:
      - mongo
  photo:
    env_file: 
      - ./photo-service/.env
    build: ./photo-service/.
    ports:
      - "${PHOTO_PORT}:${PHOTO_PORT}"
    depends_on: 
      - minio
      - rabbitmq
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - c:/data/db:/data/db
      - c:/data/configdb:/data/configdb
  minio:
    image: minio/minio
    volumes:
      - c:/data/data1:/data1
    ports:
      - "9000:9000"
    command: server minio/data1
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
