http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  customer:
    - host: '*'
    - paths:
      - '/api/v1/customer'
      - '/api/v1/customer/*'
      - '/customer-swagger'
  user:
    - host: '*'
    - paths:
      - '/api/v1/user'
      - '/api/v1/user/*'
      - '/user-swagger'
  photo:
    - host: '*'
    - paths:
      - '/api/v1/photo'
      - '/api/v1/photo/*'
      - '/photo-swagger'
  storage:
    - host: '*'
    - paths: '/photos/*'
serviceEndpoints:
  customer:
    url: 'http://customer:1500'
  user:
    url: 'http://user:2020'
  photo:
    url: 'http://photo:3333'
  storage:
    url: 'http://minio:9000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - customer
      - user
      - photo
      - storage
    policies:
      - proxy:
          - 
            condition:
              name: pathMatch
              pattern: ".*/user(-swagger)?(/.*)?"
            action:
              serviceEndpoint: user
              changeOrigin: true
          - 
            condition:
              name: pathMatch
              pattern: ".*/customer(-swagger)?(/.*)?"
            action:
              serviceEndpoint: customer
              changeOrigin: true
          - 
            condition:
              name: pathMatch
              pattern: ".*/photo(-swagger)?(/.*)?"
            action:
              serviceEndpoint: photo
              changeOrigin: true
          - 
            condition:
              name: pathMatch
              pattern: ".*/photos/.*"
            action:
              serviceEndpoint: storage
              changeOrigin: true
